# Generated by Django 3.1.2 on 2020-10-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Img1',
            field=models.ImageField(default='String', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='Img2',
            field=models.ImageField(default='String', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='Img3',
            field=models.ImageField(default='String', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='sell',
            field=models.CharField(default='sell', max_length=255),
        ),
    ]
