# Generated by Django 3.1.2 on 2020-10-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201029_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
