# Generated by Django 3.1.2 on 2020-10-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Img1',
            field=models.ImageField(default='images/no-image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Img2',
            field=models.ImageField(default='images/no-image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Img3',
            field=models.ImageField(default='images/no-image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('books/notes', 'Books/Notes'), ('stationery/equipments', 'Stationery/Equipments'), ('cycles', 'Cycles'), ('others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=2083),
        ),
    ]
