# Generated by Django 3.1.2 on 2020-11-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201029_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Books/Notes', 'Books/Notes'), ('Household', 'Household'), ('Electronics', 'Electronics'), ('Stationery/Equipments', 'Stationery/Equipments'), ('Sports, Fitness and Outdoors', 'Sports, Fitness and Outdoors'), ('Others', 'Others')], max_length=255),
        ),
    ]
