# Generated by Django 3.1.2 on 2020-11-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='username',
            new_name='buyer',
        ),
    ]
