# Generated by Django 3.1.2 on 2020-11-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201112_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='username',
            new_name='buyer',
        ),
    ]
